import { z } from "zod";

import compact from "./crop-dictionary.compact.json";

/**
 * The compact Crop Dictionary (CONTEXT.md "Crop Dictionary"): the fixed list of
 * field crops the AI may recommend from. Generated by
 * `bun run build:crop-dictionary` from `resources/culturi/crop-dictionary.json`;
 * do not edit the JSON by hand.
 */
export const cropDictionary = compact;

export type CompactCrop = (typeof compact.crops)[number];

/**
 * Every Crop id in the dictionary, in file order. Spelled out so `CropId` is
 * a real union (a JSON import widens to `string`); `crop-dictionary-ids.test`
 * pins this list to the JSON, so a regenerated dictionary fails loudly here.
 */
export const CROP_IDS = [
  "grau_toamna",
  "grau_primavara",
  "orz_toamna",
  "orzoaica_primavara",
  "porumb",
  "sorg",
  "ovaz",
  "secara",
  "triticale",
  "orez",
  "floarea_soarelui",
  "rapita_toamna",
  "soia",
  "sfecla_zahar",
  "in_ulei",
  "canepa",
  "mazare",
  "fasole",
  "naut",
  "linte",
  "lucerna",
  "trifoi",
] as const;

/** A Crop id that exists in the Crop Dictionary. */
export const cropIdSchema = z.enum(CROP_IDS);
export type CropId = z.infer<typeof cropIdSchema>;

export function isCropId(value: string): value is CropId {
  return (CROP_IDS as readonly string[]).includes(value);
}

export function getCrop(id: CropId): CompactCrop {
  const crop = compact.crops.find((c) => c.id === id);
  if (!crop) throw new Error(`Unknown crop id: ${id}`);
  return crop;
}

/** Names of the Varieties listed for a Crop (may be empty: e.g. `linte`). */
export function varietyNames(id: CropId): string[] {
  const crop = getCrop(id) as { varieties?: { name?: string }[] };
  return (crop.varieties ?? [])
    .map((v) => v.name)
    .filter((name): name is string => typeof name === "string");
}
